/**
 * Portfolio seed script — populates portfolio projects using real frontend assets
 * Run: npx tsx src/database/seedPortfolio.ts
 */

import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';
dotenv.config();

const prisma = new PrismaClient();

const projects = [
  // ── Brand Design ─────────────────────────────────────────────────
  {
    title: 'Brand Identity — Alta Counseling Ethiopia',
    slug: 'brand-identity-alta-counseling-ethiopia',
    category: 'brand-design',
    thumbnail: '/Portfolio/Brand Design/Brand Identity - Alta Counseling Ethiopia.webp',
    client: 'Alta Counseling',
    industry: 'Healthcare / Mental Health',
    year: 2023,
    shortDescription: 'A calming, professional brand identity for a leading counseling center in Ethiopia.',
    fullDescription: 'Alta Counseling needed a refreshed brand identity that communicated trust, calmness, and professionalism. We redesigned the brand using a restrained color palette, clean typography, and a cohesive visual system that works across digital and print materials.',
    servicesProvided: ['Brand Identity', 'Logo Design', 'Visual System', 'Print Materials'],
    featured: true,
    published: true,
    displayOrder: 0,
  },
  {
    title: 'Brand Identity — Raya Hotel & Convention Center',
    slug: 'brand-identity-raya-hotel',
    category: 'brand-design',
    thumbnail: '/Portfolio/Brand Design/Brand Identity - Raya Hotel & Convention Center.webp',
    client: 'Raya Hotel & Convention Center',
    industry: 'Hospitality',
    year: 2023,
    shortDescription: 'Full brand identity for a premier hotel and convention center.',
    fullDescription: 'Raya Hotel & Convention Center required a distinguished brand identity that reflected luxury and professionalism. We developed a complete visual system including logo, color palette, typography, and branded collateral.',
    servicesProvided: ['Brand Identity', 'Logo Design', 'Stationery Design'],
    featured: true,
    published: true,
    displayOrder: 1,
  },
  {
    title: 'Brand Identity — Criterion In Home Care (USA)',
    slug: 'brand-identity-criterion-in-home-care',
    category: 'brand-design',
    thumbnail: '/Portfolio/Brand Design/Criterion In Home Care - USA.webp',
    client: 'Criterion In Home Care',
    industry: 'Healthcare',
    year: 2023,
    shortDescription: 'A warm, trustworthy brand identity for a US-based home care service.',
    fullDescription: 'Criterion In Home Care needed a brand that felt approachable and trustworthy for their clients and families. We created a clean identity with a compassionate tone, designed for both digital and print use.',
    servicesProvided: ['Brand Identity', 'Logo Design', 'Brand Guidelines'],
    featured: false,
    published: true,
    displayOrder: 2,
  },
  {
    title: 'Brand Identity — Digital Deresegn',
    slug: 'brand-identity-digital-deresegn',
    category: 'brand-design',
    thumbnail: '/Portfolio/Brand Design/Digital Deresegn.webp',
    client: 'Digital Deresegn',
    industry: 'Digital Design Studio',
    year: 2024,
    shortDescription: 'A sharp, modern brand identity for a creative digital studio.',
    fullDescription: 'Digital Deresegn needed a brand that set them apart in the creative and tech space. We crafted a bold identity that communicates innovation and creativity across all touchpoints.',
    servicesProvided: ['Brand Identity', 'Logo Design', 'Social Media Kit'],
    featured: true,
    published: true,
    displayOrder: 3,
  },
  {
    title: 'Full Brand Identity — Swan Clothing',
    slug: 'brand-identity-swan-clothing',
    category: 'brand-design',
    thumbnail: '/Portfolio/Brand Design/Full brand identity for swan clothing.webp',
    client: 'Swan Clothing',
    industry: 'Fashion & Apparel',
    year: 2024,
    shortDescription: 'A complete brand identity for a modern clothing brand.',
    fullDescription: 'Swan Clothing needed a full brand identity that felt elegant yet contemporary. We developed the logo, color system, typography, and brand guidelines to give the brand a consistent presence across all platforms.',
    servicesProvided: ['Brand Identity', 'Logo Design', 'Brand Guidelines', 'Packaging Concepts'],
    featured: false,
    published: true,
    displayOrder: 4,
  },
  {
    title: 'Brand Identity — Medavail Pharmaceutical Import & Wholesale',
    slug: 'brand-identity-medavail-pharmaceutical',
    category: 'brand-design',
    thumbnail: '/Portfolio/Brand Design/Medavail Pharmaceutical Import & Wholesale.webp',
    client: 'Medavail Pharmaceuticals',
    industry: 'Pharmaceutical',
    year: 2023,
    shortDescription: 'A corporate, trustworthy brand identity for a pharmaceutical company.',
    fullDescription: 'Medavail required a serious, professional brand identity that conveyed credibility and trust in the pharmaceutical sector. We designed a clean identity system that works across corporate and medical contexts.',
    servicesProvided: ['Brand Identity', 'Logo Design', 'Corporate Stationery'],
    featured: false,
    published: true,
    displayOrder: 5,
  },

  // ── Social Media Design ───────────────────────────────────────────
  {
    title: 'Social Media Design — Niqat Coffee',
    slug: 'social-media-niqat-coffee',
    category: 'social-media-design',
    thumbnail: '/Portfolio/Social Media Design/Social Media Design for niqat coffee-11.webp',
    client: 'Niqat Coffee',
    industry: 'Coffee & Beverage',
    year: 2024,
    shortDescription: 'Consistent and engaging social media content for Niqat Coffee.',
    fullDescription: 'We created the social media accounts for Niqat Coffee from scratch, defined a visual direction, and produced consistent content that aligned with the brand\'s warm, artisan personality.',
    servicesProvided: ['Social Media Design', 'Content Creation', 'Visual Strategy'],
    featured: true,
    published: true,
    displayOrder: 6,
  },
  {
    title: 'Social Media Design — Finix Bet',
    slug: 'social-media-finix-bet',
    category: 'social-media-design',
    thumbnail: '/Portfolio/Social Media Design/Social Media Design For Finix Bet-3.webp',
    client: 'Finix Bet',
    industry: 'Entertainment / Gaming',
    year: 2024,
    shortDescription: 'Bold and dynamic social media visuals for Finix Bet.',
    fullDescription: 'Finix Bet needed high-impact social media content that matched their energetic brand. We designed a series of bold, attention-grabbing posts and templates optimised for engagement.',
    servicesProvided: ['Social Media Design', 'Template Design', 'Campaign Visuals'],
    featured: false,
    published: true,
    displayOrder: 7,
  },
  {
    title: 'Social Media Template — PTGR',
    slug: 'social-media-template-ptgr',
    category: 'social-media-design',
    thumbnail: '/Portfolio/Social Media Design/Social Media Template - PTGR.webp',
    client: 'PTGR',
    industry: 'Business Services',
    year: 2024,
    shortDescription: 'A clean, professional social media template system for PTGR.',
    fullDescription: 'We developed a reusable social media template system for PTGR that maintains brand consistency across all posts while allowing flexibility for different content types.',
    servicesProvided: ['Social Media Templates', 'Brand Consistency', 'Content Design'],
    featured: false,
    published: true,
    displayOrder: 8,
  },
  {
    title: 'Social Media Template — Task Plug',
    slug: 'social-media-template-task-plug',
    category: 'social-media-design',
    thumbnail: '/Portfolio/Social Media Design/Social Media Template - Task Plug.webp',
    client: 'Task Plug',
    industry: 'Freelance / Services Marketplace',
    year: 2024,
    shortDescription: 'Vibrant social media templates for a freelance services platform.',
    fullDescription: 'Task Plug needed social media templates that felt modern and approachable. We designed a flexible system of templates that works across promotional, informational, and community content.',
    servicesProvided: ['Social Media Templates', 'Visual Design', 'Brand Application'],
    featured: false,
    published: true,
    displayOrder: 9,
  },
  {
    title: 'Social Media Design — Ace Stainless Steel',
    slug: 'social-media-ace-stainless-steel',
    category: 'social-media-design',
    thumbnail: '/Portfolio/Social Media Design/Social Media Design For Ace Stainless Still-2.webp',
    client: 'Ace Stainless Steel',
    industry: 'Manufacturing / Industrial',
    year: 2024,
    shortDescription: 'Clean, industrial social media visuals for Ace Stainless Steel.',
    fullDescription: 'We created a suite of social media designs for Ace Stainless Steel that communicated quality and reliability, using a strong industrial aesthetic to appeal to their B2B audience.',
    servicesProvided: ['Social Media Design', 'B2B Visual Content'],
    featured: false,
    published: true,
    displayOrder: 10,
  },

  // ── Packaging & Environmental Design ─────────────────────────────
  {
    title: 'Coffee Packaging — Niqat Coffee',
    slug: 'packaging-niqat-coffee',
    category: 'packaging-environmental-design',
    thumbnail: '/Portfolio/Packaging & Enviromental Design/Coffee Packaging Bag - Niqat Coffee.webp',
    client: 'Niqat Coffee',
    industry: 'Coffee & Beverage',
    year: 2024,
    shortDescription: 'Premium coffee bag packaging design for Niqat Coffee.',
    fullDescription: 'We designed artisan coffee bag packaging for Niqat Coffee that captures the story and quality of their beans. The design balances contemporary aesthetics with Ethiopian coffee heritage.',
    servicesProvided: ['Packaging Design', 'Print Preparation', 'Brand Application'],
    featured: true,
    published: true,
    displayOrder: 11,
  },
  {
    title: 'Coffee Packaging — Toco Speciality Coffee',
    slug: 'packaging-toco-speciality-coffee',
    category: 'packaging-environmental-design',
    thumbnail: '/Portfolio/Packaging & Enviromental Design/Coffee Packaging Bag - Toca Speciality Coffee .webp',
    client: 'Toco Speciality Coffee',
    industry: 'Speciality Coffee',
    year: 2024,
    shortDescription: 'Distinctive packaging for a premium speciality coffee brand.',
    fullDescription: 'Toco Speciality Coffee needed packaging that stood out on shelves and told their brand story. We created elegant, distinctive packaging that elevated the product and made it instantly recognizable.',
    servicesProvided: ['Packaging Design', 'Brand Identity Application', 'Print Ready Files'],
    featured: true,
    published: true,
    displayOrder: 12,
  },
  {
    title: 'Coffee Packaging — Maleda Coffee',
    slug: 'packaging-maleda-coffee',
    category: 'packaging-environmental-design',
    thumbnail: '/Portfolio/Packaging & Enviromental Design/Packaging For Maleda Coffee.webp',
    client: 'Maleda Coffee',
    industry: 'Coffee & Beverage',
    year: 2024,
    shortDescription: 'Warm and earthy packaging design for Maleda Coffee.',
    fullDescription: 'Maleda Coffee needed packaging that reflected the origin and quality of their product. We designed warm, earthy packaging that connects the consumer to the Ethiopian coffee experience.',
    servicesProvided: ['Packaging Design', 'Print Preparation'],
    featured: false,
    published: true,
    displayOrder: 13,
  },
  {
    title: 'Product & Packaging — Raya',
    slug: 'packaging-raya',
    category: 'packaging-environmental-design',
    thumbnail: '/Portfolio/Packaging & Enviromental Design/Product & Packaging - Raya.webp',
    client: 'Raya Hotel & Convention Center',
    industry: 'Hospitality',
    year: 2023,
    shortDescription: 'Product and packaging design extending the Raya hotel brand.',
    fullDescription: 'Following the brand identity project, we extended Raya\'s visual language into product and packaging design — creating a cohesive branded experience for hotel merchandise and amenities.',
    servicesProvided: ['Packaging Design', 'Product Design', 'Brand Extension'],
    featured: false,
    published: true,
    displayOrder: 14,
  },
  {
    title: 'Product Packaging — Lensa Fashion',
    slug: 'packaging-lensa-fashion',
    category: 'packaging-environmental-design',
    thumbnail: '/Portfolio/Packaging & Enviromental Design/Product Packaging for Lensa Fashion.webp',
    client: 'Lensa Fashion',
    industry: 'Fashion & Apparel',
    year: 2024,
    shortDescription: 'Elegant product packaging for a fashion brand.',
    fullDescription: 'Lensa Fashion needed packaging that felt as premium as their clothing line. We designed refined packaging that reflected the brand\'s style and created a memorable unboxing experience.',
    servicesProvided: ['Packaging Design', 'Brand Application'],
    featured: false,
    published: true,
    displayOrder: 15,
  },
  {
    title: 'Rollup Banner — Toco Speciality Coffee',
    slug: 'rollup-toco-speciality-coffee',
    category: 'packaging-environmental-design',
    thumbnail: '/Portfolio/Packaging & Enviromental Design/Toco Speciality Coffee Rollup Banner.webp',
    client: 'Toco Speciality Coffee',
    industry: 'Speciality Coffee',
    year: 2024,
    shortDescription: 'Eye-catching rollup banner for events and in-store display.',
    fullDescription: 'We designed a bold rollup banner for Toco Speciality Coffee that commands attention at events and in-store. The design maintains brand consistency while maximizing visual impact in a vertical format.',
    servicesProvided: ['Environmental Design', 'Event Collateral', 'Print Design'],
    featured: false,
    published: true,
    displayOrder: 16,
  },

  // ── Print & Layout Design ─────────────────────────────────────────
  {
    title: 'Business Card — Raya Hotel',
    slug: 'business-card-raya-hotel',
    category: 'print-layout',
    thumbnail: '/Portfolio/Print & Layout Design/Business Card - Raya.webp',
    client: 'Raya Hotel & Convention Center',
    industry: 'Hospitality',
    year: 2023,
    shortDescription: 'Elegant business card design as part of the Raya brand system.',
    fullDescription: 'As part of the wider Raya Hotel brand identity project, we designed premium business cards that reflect the hotel\'s commitment to quality and leave a lasting impression.',
    servicesProvided: ['Business Card Design', 'Print Preparation'],
    featured: false,
    published: true,
    displayOrder: 17,
  },
  {
    title: 'Business Profile Cover — Prime Ethiopia',
    slug: 'business-profile-prime-ethiopia',
    category: 'print-layout',
    thumbnail: '/Portfolio/Print & Layout Design/Business Profile Cover Prime Ethiopia .webp',
    client: 'Prime All',
    industry: 'Corporate Services',
    year: 2023,
    shortDescription: 'A professional business profile cover that makes a strong first impression.',
    fullDescription: 'Prime Ethiopia needed a business profile cover that conveyed authority and professionalism. We designed a cover that balances strong visual impact with clear brand communication.',
    servicesProvided: ['Print Design', 'Layout Design', 'Corporate Collateral'],
    featured: false,
    published: true,
    displayOrder: 18,
  },
  {
    title: 'Company Profile — CCI, Utop & Goozam',
    slug: 'company-profile-cci-utop-goozam',
    category: 'print-layout',
    thumbnail: '/Portfolio/Print & Layout Design/company-profile-cci-utop-goozam.webp',
    client: 'CCI / Utop / Goozam',
    industry: 'Technology & Business',
    year: 2024,
    shortDescription: 'Multi-brand company profile design for three organisations.',
    fullDescription: 'We designed company profiles for CCI, Utop, and Goozam — each tailored to their unique brand identity while maintaining consistent quality and professionalism across all three documents.',
    servicesProvided: ['Company Profile Design', 'Layout Design', 'Print Preparation'],
    featured: false,
    published: true,
    displayOrder: 19,
  },
  {
    title: 'Course Outline — Center for Computer Intelligence (USA)',
    slug: 'course-outline-cci-usa',
    category: 'print-layout',
    thumbnail: '/Portfolio/Print & Layout Design/Course Outline - Center For Computer Intelligence (CCI) (USA).webp',
    client: 'Center for Computer Intelligence',
    industry: 'Education / Technology',
    year: 2024,
    shortDescription: 'A structured, professional course outline layout for a US-based tech education centre.',
    fullDescription: 'CCI needed a course outline document that was clear, structured, and professionally designed. We created a clean layout that guides students through the content hierarchy while maintaining a strong institutional identity.',
    servicesProvided: ['Document Design', 'Layout Design', 'Print Preparation'],
    featured: false,
    published: true,
    displayOrder: 20,
  },
  {
    title: 'Flyer — Prime Ethiopia',
    slug: 'flyer-prime-ethiopia',
    category: 'print-layout',
    thumbnail: '/Portfolio/Print & Layout Design/Flyer Prime Ethiopia.webp',
    client: 'Prime All',
    industry: 'Corporate Services',
    year: 2023,
    shortDescription: 'A clean, impactful promotional flyer for Prime Ethiopia.',
    fullDescription: 'We designed a promotional flyer for Prime Ethiopia that communicated their services clearly and confidently, with a layout that guides the reader\'s eye to the key message.',
    servicesProvided: ['Flyer Design', 'Print Design'],
    featured: false,
    published: true,
    displayOrder: 21,
  },
  {
    title: 'Trifold Brochure — PTGR',
    slug: 'trifold-ptgr',
    category: 'print-layout',
    thumbnail: '/Portfolio/Print & Layout Design/Trifold PTGR.webp',
    client: 'PTGR',
    industry: 'Business Services',
    year: 2024,
    shortDescription: 'A well-structured trifold brochure for PTGR.',
    fullDescription: 'We designed a trifold brochure for PTGR that presents their services in a logical, visually engaging flow. Each panel was carefully considered to guide the reader from introduction to call to action.',
    servicesProvided: ['Brochure Design', 'Layout Design', 'Print Preparation'],
    featured: false,
    published: true,
    displayOrder: 22,
  },

  // ── Web & UI Design ───────────────────────────────────────────────
  {
    title: 'Website Banner — Finix Bet',
    slug: 'website-banner-finix-bet',
    category: 'web-ui-design',
    thumbnail: '/Portfolio/Web Design/Website Banner For Finix Bet-10.webp',
    client: 'Finix Bet',
    industry: 'Entertainment / Gaming',
    year: 2024,
    shortDescription: 'High-impact website banners for an online betting platform.',
    fullDescription: 'We designed a series of bold, conversion-focused website banners for Finix Bet. Each banner was crafted to capture attention immediately and drive user engagement on the platform.',
    servicesProvided: ['Web Banner Design', 'UI Design', 'Digital Marketing Assets'],
    featured: false,
    published: true,
    displayOrder: 23,
  },
];

async function seedPortfolio() {
  console.log('🌱 Seeding portfolio projects…');
  let created = 0;
  let skipped = 0;

  for (const project of projects) {
    const existing = await prisma.portfolioProject.findUnique({ where: { slug: project.slug } });
    if (existing) { skipped++; continue; }

    await prisma.portfolioProject.create({ data: project });
    created++;
  }

  console.log(`✅ Done — ${created} created, ${skipped} already existed.`);
  await prisma.$disconnect();
}

seedPortfolio().catch((e) => {
  console.error('Seed error:', e);
  prisma.$disconnect();
  process.exit(1);
});
